### PR TITLE
Remove PHP 5.6 support

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #161

### CODE REVIEW

**Comment by patrickjahns** [comment]
@phil-davis 
When it's green, please add it to the nightlies as well - as this app moves forward into being released soon(tm)

**Comment by phil-davis** [comment]
@patrickjahns can you give me some history? How is this different from files_primary_s3?
Which have been released in the past?
Which is the "future" and which is old to-be-deprecated?
And anything else I should know...

**Comment by PVince81** [comment]
@phil-davis files_external_s3 is the "external storage" variant. so it's extra mount points on top of the regular storage like files_external_dropbox, files_external_ftp. The other app files_primary_s3 replaces the home storage and the storage format is different.

the app files_external_s3 is new and was never released, it's basically extracted from core's "apps/files_external" into this repo. we didn't go forward with the release yet and would like to do so soon, hence this ticket for preparation

**Comment by patrickjahns** [comment]
As vincent already mentioned - brings me also to the point - can we use our acceptance tests from/for core to test things like create/renaming files for this application in that mountpoint?

Additionally wondering if we have tests doing a "cross-storage move" - meaning move a file from this external folder into local storage ( vice-versa ). Also what happens to versions and trashbin.
Might be worth a separate QA ticket to be scheduled for the future then

**Comment by PVince81** [comment]
please note that we already have integration tests in PHPUnit which connects to a S3 bucket. the test was moved from core to this repo as well.
they only cover direct storage operations and don't involve higher level things like trashbin and versions

**Comment by phil-davis** [comment]
In this PR, I will concentrate on getting existing tests green. After that we can work on adding other tests...

**Comment by patrickjahns** [comment]
@phil-davis 
Which ticket should we comment about additions?

**Comment by individual-it** [comment]
I could not make unit test work with minio, so disabled it for now.
We should make CI pass in the first step and then can work on the other issue. CI issues blocking other PRs

**Comment by phil-davis** [comment]
Note: I got stuck some time ago trying to work out why the tests hang with `minio`. I tried changing the port, and verified that indeed that caused an immediate fail. So when the host:port details were correct, the test software was (at least attempting) to access `minio` and for some reason it just sits waiting for `minio` to respond. There seems to be no response, and after 1 hour the drone job is cancelled.

What @individual-it has done seems the best for now - disable the `minio` drone matrix job.

Someone please review - @DeepDiver1975 @PVince81 @patrickjahns @micbar or whoever.

**Comment by phil-davis** [comment]
Issue for `minio` problem is #162

**Pull request merged**
