### PR TITLE
Update aws library to 3.93

### PR DESCRIPTION
**Pull request by jvillafanez**
Quick test: upload, download, and create folder against a scality server, no problems found

### CODE REVIEW

**Comment by jvillafanez** [comment]
It seems there are problems with the CI, the app can't be installed... maybe we should wait for https://github.com/owncloud/files_external_s3/pull/162 ?

**Comment by individual-it** [comment]
I've made #162 pass CI, please have a look

**Comment by individual-it** [comment]
rebased, over merged #162 - lets see what CI says

**Comment by individual-it** [comment]
@jvillafanez tests pass, taking off my assignment

**Comment by micbar** [comment]
@jvillafanez is this PR ready? Please ping someone for review.

**Comment by jvillafanez** [comment]
yes, this is ready. Pinging @DeepDiver1975

**Pull request merged**
